# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.IntegerField(db_column='StoreCode')),
                ('point_location', django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326)),
            ],
        ),
    ]
