# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managetasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldBorder',
            new_name='PointsCore',
        ),
    ]
