# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managetasks', '0004_auto_20170322_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointscore',
            name='added_by',
            field=models.IntegerField(db_column='pointAdder', default=1),
        ),
        migrations.AddField(
            model_name='pointscore',
            name='guid',
            field=models.CharField(db_column='guid', default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pointscore',
            name='modified_by',
            field=models.IntegerField(db_column='editPerson', default=1),
        ),
        migrations.AddField(
            model_name='pointscore',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, db_column='editTime', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
